export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        property="og:description"
        content="Black Stories - OSS powered by Vercel and OpenAI"
      />
      <meta property="og:image" content="/api/og" />
    </>
  );
}
